[[craft_recipes]]
recipe_id = 1
station_structure_id = 201
output_item_id = 2
output_quantity = 1
craft_minutes = 1.0
ingredients = [{ item_id = 1, quantity = 1 }, { item_id = 10, quantity = 2 }]

[[craft_recipes]]
recipe_id = 2
station_structure_id = 202
output_item_id = 11
output_quantity = 1
craft_minutes = 1.5
ingredients = [{ item_id = 8, quantity = 4 }, { item_id = 9, quantity = 2 }]

[[craft_recipes]]
recipe_id = 3
station_structure_id = 202
output_item_id = 12
output_quantity = 1
craft_minutes = 2.0
ingredients = [{ item_id = 8, quantity = 5 }, { item_id = 9, quantity = 3 }]

[[craft_recipes]]
recipe_id = 4
station_structure_id = 202
output_item_id = 13
output_quantity = 1
craft_minutes = 1.0
ingredients = [{ item_id = 8, quantity = 3 }, { item_id = 9, quantity = 2 }]

[[craft_recipes]]
recipe_id = 5
station_structure_id = 202
output_item_id = 14
output_quantity = 1
craft_minutes = 1.0
ingredients = [{ item_id = 8, quantity = 2 }, { item_id = 9, quantity = 1 }]
