[[phone_listings]]
site_id = 1
listing_id = 1
listing_kind = "BuyItem"
item_or_unlockable_id = 1
quantity = 6

[[phone_listings]]
site_id = 1
listing_id = 2
listing_kind = "BuyItem"
item_or_unlockable_id = 2
quantity = 5

[[phone_listings]]
site_id = 1
listing_id = 3
listing_kind = "BuyItem"
item_or_unlockable_id = 3
quantity = 4

[[phone_listings]]
site_id = 1
listing_id = 4
listing_kind = "BuyItem"
item_or_unlockable_id = 4
quantity = 10

[[phone_listings]]
site_id = 1
listing_id = 5
listing_kind = "BuyItem"
item_or_unlockable_id = 5
quantity = 8

[[phone_listings]]
site_id = 1
listing_id = 6
listing_kind = "BuyItem"
item_or_unlockable_id = 6
quantity = 8

[[phone_listings]]
site_id = 1
listing_id = 7
listing_kind = "BuyItem"
item_or_unlockable_id = 7
quantity = 6

[[phone_listings]]
site_id = 1
listing_id = 8
listing_kind = "BuyItem"
item_or_unlockable_id = 8
quantity = 12

[[phone_listings]]
site_id = 1
listing_id = 9
listing_kind = "BuyItem"
item_or_unlockable_id = 9
quantity = 10

[[phone_listings]]
site_id = 1
listing_id = 10
listing_kind = "HireContractor"
item_or_unlockable_id = 0
price = 8
quantity = 3

[[phone_listings]]
site_id = 1
listing_id = 11
listing_kind = "BuyItem"
item_or_unlockable_id = 16
quantity = 8

[[phone_listings]]
site_id = 1
listing_id = 12
listing_kind = "BuyItem"
item_or_unlockable_id = 17
quantity = 8

[[phone_listings]]
site_id = 1
listing_id = 13
listing_kind = "BuyItem"
item_or_unlockable_id = 18
quantity = 6

[[phone_listings]]
site_id = 1
listing_id = 14
listing_kind = "BuyItem"
item_or_unlockable_id = 19
quantity = 6

[[phone_listings]]
site_id = 1
listing_id = 15
listing_kind = "BuyItem"
item_or_unlockable_id = 20
quantity = 4

[[phone_listings]]
site_id = 1
listing_id = 16
listing_kind = "BuyItem"
item_or_unlockable_id = 15
quantity = 8

[[phone_listings]]
site_id = 1
listing_id = 17
listing_kind = "BuyItem"
item_or_unlockable_id = 39
quantity = 3
