[[task_templates]]
task_template_id = 1
publisher_faction_id = 2
task_tier_id = 1
progress_kind = "RestorationTiles"
target_amount_min = 0
target_amount_max = 0
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 2
publisher_faction_id = 1
task_tier_id = 1
progress_kind = "BuyItem"
target_amount_min = 1
target_amount_max = 3
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 3
publisher_faction_id = 1
task_tier_id = 1
progress_kind = "SellItem"
target_amount_min = 1
target_amount_max = 3
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 4
publisher_faction_id = 1
task_tier_id = 1
progress_kind = "TransferItem"
target_amount_min = 1
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 5
publisher_faction_id = 2
task_tier_id = 1
progress_kind = "PlantItem"
target_amount_min = 2
target_amount_max = 5
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 6
publisher_faction_id = 3
task_tier_id = 1
progress_kind = "CraftRecipe"
target_amount_min = 1
target_amount_max = 3
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 7
publisher_faction_id = 1
task_tier_id = 1
progress_kind = "ConsumeItem"
target_amount_min = 1
target_amount_max = 3
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 21
publisher_faction_id = 1
task_tier_id = 1
progress_kind = "PerformAction"
target_amount_min = 2
target_amount_max = 5
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 22
publisher_faction_id = 1
task_tier_id = 2
progress_kind = "KeepAllWorkerMetersAboveForDuration"
target_amount_min = 3
target_amount_max = 7
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 85.0
threshold_value_max = 95.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 23
publisher_faction_id = 1
task_tier_id = 2
progress_kind = "KeepTileMoistureAtLeastForDuration"
target_amount_min = 3
target_amount_max = 6
required_count_min = 3
required_count_max = 6
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 50.0
threshold_value_max = 70.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 24
publisher_faction_id = 1
task_tier_id = 1
progress_kind = "EarnMoney"
target_amount_min = 6
target_amount_max = 15
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 25
publisher_faction_id = 2
task_tier_id = 1
progress_kind = "PlantAny"
target_amount_min = 4
target_amount_max = 8
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 26
publisher_faction_id = 2
task_tier_id = 2
progress_kind = "PlantCountAtDensity"
target_amount_min = 2
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 55.0
threshold_value_max = 85.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 27
publisher_faction_id = 2
task_tier_id = 2
progress_kind = "AnyPlantDensityAtLeast"
target_amount_min = 3
target_amount_max = 6
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 80.0
threshold_value_max = 95.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 28
publisher_faction_id = 2
task_tier_id = 2
progress_kind = "PlantWindProtectionAtLeast"
target_amount_min = 2
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 35.0
threshold_value_max = 55.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 29
publisher_faction_id = 2
task_tier_id = 2
progress_kind = "PlantHeatProtectionAtLeast"
target_amount_min = 2
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 35.0
threshold_value_max = 55.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 30
publisher_faction_id = 2
task_tier_id = 2
progress_kind = "PlantDustProtectionAtLeast"
target_amount_min = 2
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 35.0
threshold_value_max = 55.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 31
publisher_faction_id = 2
task_tier_id = 2
progress_kind = "NearbyPopulatedPlantTilesAtLeast"
target_amount_min = 3
target_amount_max = 6
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 32
publisher_faction_id = 3
task_tier_id = 1
progress_kind = "CraftAnyItem"
target_amount_min = 2
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 33
publisher_faction_id = 3
task_tier_id = 2
progress_kind = "SellCraftedItem"
target_amount_min = 1
target_amount_max = 3
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 34
publisher_faction_id = 3
task_tier_id = 1
progress_kind = "BuildStructure"
target_amount_min = 1
target_amount_max = 2
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 35
publisher_faction_id = 3
task_tier_id = 1
progress_kind = "BuildStructure"
target_amount_min = 1
target_amount_max = 2
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 36
publisher_faction_id = 3
task_tier_id = 2
progress_kind = "BuildAnyStructure"
target_amount_min = 2
target_amount_max = 4
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 37
publisher_faction_id = 3
task_tier_id = 2
progress_kind = "BuildStructureSet"
target_amount_min = 3
target_amount_max = 3
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 0.0
threshold_value_max = 0.0
completion_faction_reputation_delta = 0

[[task_templates]]
task_template_id = 38
publisher_faction_id = 3
task_tier_id = 2
progress_kind = "KeepAllDevicesIntegrityAboveForDuration"
target_amount_min = 4
target_amount_max = 8
required_count_min = 0
required_count_max = 0
item_id = 0
plant_id = 0
recipe_id = 0
structure_id = 0
secondary_structure_id = 0
tertiary_structure_id = 0
action_kind = "None"
threshold_value_min = 50.0
threshold_value_max = 80.0
completion_faction_reputation_delta = 0

