[[total_reputation_tiers]]
tier_index = 1
reputation_requirement = 10
display_name = "Reputation Tier I"

[[total_reputation_tiers]]
tier_index = 2
reputation_requirement = 25
display_name = "Reputation Tier II"

[[total_reputation_tiers]]
tier_index = 3
reputation_requirement = 45
display_name = "Reputation Tier III"
