#pragma once

#include <cstdint>

namespace gs1
{
enum SiteProjectionUpdateFlags : std::uint64_t
{
    SITE_PROJECTION_UPDATE_NONE = 0,
    SITE_PROJECTION_UPDATE_TILES = 1ull << 0,
    SITE_PROJECTION_UPDATE_WORKER = 1ull << 1,
    SITE_PROJECTION_UPDATE_CAMP = 1ull << 2,
    SITE_PROJECTION_UPDATE_WEATHER = 1ull << 3,
    SITE_PROJECTION_UPDATE_HUD = 1ull << 4,
    SITE_PROJECTION_UPDATE_INVENTORY = 1ull << 5,
    SITE_PROJECTION_UPDATE_TASKS = 1ull << 6,
    SITE_PROJECTION_UPDATE_PHONE = 1ull << 7,
    SITE_PROJECTION_UPDATE_CRAFT_CONTEXT = 1ull << 8,
    SITE_PROJECTION_UPDATE_PLACEMENT_PREVIEW = 1ull << 9,
    SITE_PROJECTION_UPDATE_MODIFIERS = 1ull << 10
};
}  // namespace gs1
